In [3]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv('.\data.txt',sep='\t')

In [5]:
data = data.T

In [6]:
data

0      \
Unnamed: 0                                 chr1_3119987_3120487   
p56_rep1_GAGATTCCAGGCAGAAACTGCATATATAGCCT                     0   
p56_rep1_AGCGATAGCGTACTAGACTGCATACAGGACGT                     0   
p56_rep1_AGCGATAGACTGAGCGATCTGAGTTATAGCCT                     0   
p56_rep1_GAGATTCCATGCGCAGATCTGAGTATAGAGGC                     0   
p56_rep1_CTGAAGCTTCGACGTCCTCTCTATATAGAGGC                     0   
p56_rep1_GAGATTCCGCTCATGATATCCTCTATAGAGGC                     0   
p56_rep1_AGCGATAGACTCGCTATTATGCGATATAGCCT                     0   
p56_rep1_GAGATTCCAGGCAGAACTCTCTATCAGGACGT                     0   
p56_rep1_CGGCTATGAAGAGGCAAAGGAGTAATAGAGGC                     0   
p56_rep1_CTGAAGCTGGAGCTACATCTGAGTCAGGACGT                     0   
p56_rep1_CTGAAGCTATCTCAGGGTAAGGAGATAGAGGC                     0   
p56_rep1_CGCTCATTTCCTGAGCCCTAGAGTCAGGACGT                     0   
p56_rep1_AGCGATAGCTCTGGTAGCGTAAGACAGGACGT                     0   
p56_rep1_AGCGATAGACTCGCTATTATGCGAATAGAGGC                     0   
p56_rep1_GAGATTCCATCTCAGGAAGGAGTATATAGCCT                     0   
p56_rep1_CTGAAGCTCTCTCTACAAGGCTATATAGAGGC                     0   
p56_rep1_CTGAAGCTCGAGGCTGAAGGAGTAATAGAGGC                     1   
p56_rep1_CTGAAGCTAGGCAGAACTAAGCCTATAGAGGC                     0   
p56_rep1_GAGATTCCCTCTCTACCTAAGCCTCAGGACGT                     0   
p56_rep1_CGGCTATGTAGGCATGAAGGCTATTATAGCCT                     0   
p56_rep1_CTGAAGCTTACGCTGCCGTCTAATATAGAGGC                     0   
p56_rep1_GAGATTCCCGAGGCTGTCTCTCCGTATAGCCT                     0   
p56_rep1_ATTACTCGCGAGGCTGTTATGCGATATAGCCT                     0   
p56_rep1_GAGATTCCGGAGCTACCGTCTAATTATAGCCT                     0   
p56_rep1_GAGATTCCTAGGCATGGCGTAAGACAGGACGT                     0   
p56_rep1_CGGCTATGATCTCAGGGTAAGGAGATAGAGGC                     0   
p56_rep1_GAGATTCCGCGTAGTATCTCTCCGCAGGACGT                     0   
p56_rep1_CTGAAGCTGTAGAGGACTAAGCCTATAGAGGC                     0   
p56_rep1_GAGATTCCTAAGGCGACTCTCTATTATAGCCT                     0   
...                                                         ...   
p56_rep2_GAGATTCCTACTGCCTTAAGATCCCAGGACGT                     0   
p56_rep2_GAGATTCCTTCCATCCTGCCTTACATAGAGGC                     0   
p56_rep2_TCCGGAGATTAGCCTCATAGCCTTGGCTCTGA                     0   
p56_rep2_CGGCTATGACGAATCTATTCGTTGCAGGACGT                     0   
p56_rep2_AGCGATAGGTCATGAATTCATCCATATAGCCT                     0   
p56_rep2_TCCGCGAAGAACGGTAGGTTAGACCAGGACGT                     0   
p56_rep2_ATTCAGAACGTATAGATCCGGTAAATAGAGGC                     0   
p56_rep2_CTGAAGCTCGTATAGATTACGACCTATAGCCT                     0   
p56_rep2_TAATGCGCCAGAACTGCGAATTCCGGCTCTGA                     0   
p56_rep2_TCCGGAGAGCAACCTATCCGGTAACAGGACGT                     0   
p56_rep2_ATTACTCGGCAACCTATTGGAAGTTATAGCCT                     0   
p56_rep2_GAGATTCCGAACGGTATTCATCCACAGGACGT                     0   
p56_rep2_TCCGGAGAAAGCAACGTCCGGTAACCTATCCT                     0   
p56_rep2_AGCGATAGAAGCAACGGGATACTACCTATCCT                     0   
p56_rep2_CGCTCATTTTCCATCCGGATACTAGGCTCTGA                     0   
p56_rep2_CGGCTATGCTTCAATGTCCGGTAAATAGAGGC                     0   
p56_rep2_TCCGGAGAATAAGTCGGGATACTATATAGCCT                     0   
p56_rep2_CTGAAGCTTTCCATCCTGCCTTACCCTATCCT                     0   
p56_rep2_CGGCTATGCTAATGCTATTCGTTGTATAGCCT                     0   
p56_rep2_TCCGGAGAAAGCAACGATAGCCTTGGCTCTGA                     0   
p56_rep2_TCCGGAGAACGAATCTTGCCTTACGGCTCTGA                     0   
p56_rep2_TCCGGAGACTTCAATGTTGGAAGTCCTATCCT                     0   
p56_rep2_CGCTCATTGCAACCTATGCCTTACATAGAGGC                     0   
p56_rep2_AGCGATAGCTTCAATGGGATACTAATAGAGGC                     0   
p56_rep2_ATTCAGAAGCCTCAATTCCGGTAACCTATCCT                     0   
p56_rep2_CTGAAGCTGTCTACCAATTCGTTGTATAGCCT                     0   
p56_rep2_AGCGATAGGTCTACCAATTCGTTGATAGAGGC                     0   
p56_rep2_ATTCAGAAATAAGTCGTTGGAAGTCCTATCCT                     0   
p56_rep2_CGGCTATGTATGCCATAATGACGTTATAG

In [7]:
yDict = {}
with open('.\labels.txt') as FID:
    for line in FID:
        if len(line) < 3:
            continue
        key,val = line.strip().split('\t')
        yDict[key] = val

In [8]:
yDict

{'rep1_GAGATTCCAGGCAGAAACTGCATATATAGCCT': 'IN1',
 'rep1_AGCGATAGCGTACTAGACTGCATACAGGACGT': 'EX3',
 'rep1_AGCGATAGACTGAGCGATCTGAGTTATAGCCT': 'AC',
 'rep1_GAGATTCCATGCGCAGATCTGAGTATAGAGGC': 'EX3',
 'rep1_CTGAAGCTTCGACGTCCTCTCTATATAGAGGC': 'EX3',
 'rep1_GAGATTCCGCTCATGATATCCTCTATAGAGGC': 'IN1',
 'rep1_AGCGATAGACTCGCTATTATGCGATATAGCCT': 'AC',
 'rep1_GAGATTCCAGGCAGAACTCTCTATCAGGACGT': 'EX3',
 'rep1_CGGCTATGAAGAGGCAAAGGAGTAATAGAGGC': 'EX3',
 'rep1_CTGAAGCTGGAGCTACATCTGAGTCAGGACGT': 'IN1',
 'rep1_CTGAAGCTATCTCAGGGTAAGGAGATAGAGGC': 'EX2',
 'rep1_CGCTCATTTCCTGAGCCCTAGAGTCAGGACGT': 'EX3',
 'rep1_AGCGATAGCTCTGGTAGCGTAAGACAGGACGT': 'EX3',
 'rep1_AGCGATAGACTCGCTATTATGCGAATAGAGGC': 'MG',
 'rep1_GAGATTCCATCTCAGGAAGGAGTATATAGCCT': 'EX2',
 'rep1_CTGAAGCTCTCTCTACAAGGCTATATAGAGGC': 'EX2',
 'rep1_CTGAAGCTCGAGGCTGAAGGAGTAATAGAGGC': 'EX1',
 'rep1_CTGAAGCTAGGCAGAACTAAGCCTATAGAGGC': 'EX1',
 'rep1_GAGATTCCCTCTCTACCTAAGCCTCAGGACGT': 'OC',
 'rep1_CGGCTATGTAGGCATGAAGGCTATTATAGCCT': 'OC',
 'rep1_CTGAAGCTTACGCTGCCG

In [10]:
y= []
for k in list(data.index)[1:]:
    y.append(yDict[k[4:]])

In [11]:
len(y)

2088

In [20]:
x=data.iloc[1:,:]

In [66]:
X = np.array(x)

In [67]:
###nmf

from sklearn.decomposition import NMF        
feature = X

model = NMF(n_components=20 ,init='nndsvda', random_state=0,solver = 'mu')     
W = model.fit_transform(feature)
H = model.components_ # 系数矩阵

In [55]:
###lsnmf
import nimfa
F = X

lsnmf = nimfa.Lsnmf(F, seed="random_vcol", rank=20, max_iter=12, sub_iter=10,inner_sub_iter=10, beta=0.1)
lsnmf_fit = lsnmf()
bias = lsnmf_fit.basis() # 基矩阵
coef = lsnmf_fit.coef()
W = bias  

In [15]:
import matplotlib
matplotlib.use('agg')
from matplotlib import pyplot as plt
import seaborn as sns


def plot_embedding(X, labels, classes=None, method='tSNE', cmap='tab20', figsize=(4, 4), markersize=4, marker=None,
                   return_emb=False, save=False, save_emb=False, show_legend=True, show_axis_label=True,title = '', **legend_params):
    if marker is not None:
        X = np.concatenate([X, marker], axis=0)
    N = len(labels)
    if X.shape[1] != 2:
        if method == 'tSNE':
            from sklearn.manifold import TSNE
            X = TSNE(n_components=2, random_state=124).fit_transform(X)
        if method == 'UMAP':
            from umap import UMAP
            X = UMAP(n_neighbors=30, min_dist=0.1).fit_transform(X)
        if method == 'PCA':
            from sklearn.decomposition import PCA
            X = PCA(n_components=2, random_state=124).fit_transform(X)
        
    plt.figure(figsize=figsize)
    if classes is None:
        classes = np.unique(labels)

    if cmap is not None:
        cmap = cmap
    elif len(classes) <= 10:
        cmap = 'tab10'
    elif len(classes) <= 20:
        cmap = 'tab20'
    else:
        cmap = 'husl'
    colors = sns.color_palette(cmap, n_colors=len(classes))
        
    for i, c in enumerate(classes):
        plt.scatter(X[:N][labels==c, 0], X[:N][labels==c, 1], s=markersize, color=colors[i], label=c)
    if marker is not None:
        plt.scatter(X[N:, 0], X[N:, 1], s=10*markersize, color='black', marker='*')
#     plt.axis("off")
    plt.title(title)
    legend_params_ = {'loc': 'center left',
                     'bbox_to_anchor':(1.0, 0.45),
                     'fontsize': 10,
                     'ncol': 1,
                     'frameon': False,
                     'markerscale': 1.5
                    }
    legend_params_.update(**legend_params)
    if show_legend:
        plt.legend(**legend_params_)
    sns.despine(offset=10, trim=True)
    if show_axis_label:
        plt.xlabel(method+' dim 1', fontsize=12)
        plt.ylabel(method+' dim 2', fontsize=12)

    if save:
        plt.savefig(save, format='jpg', bbox_inches='tight',dpi=300)
    else:
        plt.show()
        
    if save_emb:
        np.savetxt(save_emb, X)
    if return_emb:
        return X
    

In L:\newdownload\anaconda\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In L:\newdownload\anaconda\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The verbose.level rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In L:\newdownload\anaconda\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The verbose.fileo rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.


In [61]:
import os
reference =r'.\labels.txt'

outdir = '..'
emb = 'UMAP'
#emb = 'tSNE'
if reference:
    ref = pd.read_csv(reference, sep='\t', header=None, index_col=0)[1]
X= plot_embedding(W, ref, method=emb, 
               save=os.path.join(outdir, 'emb_{}128lsnmf.jpg'.format(emb)), save_emb=None,return_emb = False,title ='Lsnmf 128latent')
#X= plot_embedding(W, ref, method=emb, 
#               save=os.path.join(outdir, 'emb_{}8nmf.jpg'.format(emb)), save_emb=None,return_emb = False,title ='NMF 128latent')


L:\newdownload\anaconda\lib\site-packages\ipykernel_launcher.py:23: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).


In [17]:
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 29 16:55:20 2021

@author: huangyuyao
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('agg')
from matplotlib import pyplot as plt
import seaborn as sns
import os


import scipy
from torch.utils.data import TensorDataset, DataLoader
from sklearn.metrics import f1_score
from sklearn.preprocessing import MinMaxScaler, LabelEncoder, scale
from sklearn.metrics import classification_report, confusion_matrix, adjusted_rand_score
from sklearn.metrics import normalized_mutual_info_score



def predict(features, device='cpu', method='kmeans'):
    
    from sklearn.cluster import KMeans
    feature = features 
    kmeans = KMeans(n_clusters=8, n_init=20, random_state=0)
    pred = kmeans.fit_predict(feature)

    return pred


def read_labels(ref, return_enc=False):

    # if isinstance(ref, str):
    ref = pd.read_csv(ref, sep='\t', index_col=0, header=None)

    encode = LabelEncoder()
    ref = encode.fit_transform(ref.values.squeeze())
    classes = encode.classes_
    if return_enc:
        return ref, classes, encode
    else:
        return ref, classes
    
def reassign_cluster_with_ref(Y_pred, Y):

    def reassign_cluster(y_pred, index):
        y_ = np.zeros_like(y_pred)
        for i, j in index:
            y_[np.where(y_pred==i)] = j
        return y_
    from sklearn.utils.linear_assignment_ import linear_assignment
#    print(Y_pred.size, Y.size)
    assert Y_pred.size == Y.size
    D = max(Y_pred.max(), Y.max())+1
    w = np.zeros((D,D), dtype=np.int64)
    for i in range(Y_pred.size):
        w[Y_pred[i], Y[i]] += 1
    ind = linear_assignment(w.max() - w)

    return reassign_cluster(Y_pred, ind)

def cluster_report(ref, pred, classes):

    pred = reassign_cluster_with_ref(pred, ref)
    cm = confusion_matrix(ref, pred)
    print('\n## Confusion matrix ##\n')
    print(cm)
    print('\n## Cluster Report ##\n')
    print(classification_report(ref, pred, target_names=classes))
    clust_Report = classification_report(ref, pred, target_names=classes)
    ari_score = adjusted_rand_score(ref, pred)
    NMI = normalized_mutual_info_score(ref,pred)
    print("\nAdjusted Rand score : {:.4f}".format(ari_score))
    print("\nNMI(Normalized mutual information) : {:.4f}".format(NMI))

    
    return cm,clust_Report,ari_score,NMI
    
def binarization(imputed, raw):
    return scipy.sparse.csr_matrix((imputed.T > raw.mean(1).T).T & (imputed>raw.mean(0))).astype(np.int8)




def plot_confusion_matrix(cm, x_classes=None, y_classes=None,
                          normalize=False,
                          title='',
                          cmap=plt.cm.Blues,
                          figsize=(4,4),
                          mark=True,
                          save=None,
                          rotation=45,
                          show_cbar=True,
                          show_xticks=True,
                          show_yticks=True,
                        ):

    import itertools
    from mpl_toolkits.axes_grid1.inset_locator import inset_axes


    if normalize:
        cm = cm.astype('float') / cm.sum(axis=0)[np.newaxis, :]

    fig = plt.figure(figsize=figsize)
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)

    x_tick_marks = np.arange(len(x_classes))
    #y_tick_marks = np.arange(len(y_classes))
    plt.xticks(x_tick_marks, x_classes, rotation=rotation, ha='right')
    #plt.yticks(y_tick_marks, y_classes)
    
    ax=plt.gca()
    if not show_xticks:
        ax.axes.get_xaxis().set_ticks([])
        ax.axes.get_xaxis().set_ticklabels([])
    if not show_yticks:
        ax.axes.get_yaxis().set_ticks([])
        ax.axes.get_yaxis().set_ticklabels([])
    else:
        plt.ylabel('Predicted Cluster')


    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    if mark:
        for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
            if cm[i, j] > 0.1:
                plt.text(j, i, format(cm[i, j], fmt),
                     horizontalalignment="center",
                     color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    if show_cbar:
        plt.colorbar(shrink=0.8) 
    if save:
        plt.savefig(save, format='jpg', bbox_inches='tight',dpi = 200)
    
    plt.show()



In [65]:
fea =W
pred = predict(fea)
from sklearn.metrics import silhouette_score
ss_silhouette_Score = silhouette_score(fea, pred)
print(ss_silhouette_Score)
#r = open(r'F:\RRReview_calculate\LSNMF\lsnmf128latent.txt','w')
r = open(r'...\nmf10latent.txt','w')
r.write(str(ss_silhouette_Score))
r.close()

0.33980098183832197


In [62]:
fea = W
#fea = pd.read_csv(r'G:\feature.txt', sep='\t', index_col=0, header=None)
pred = predict(fea)
reference = '.\labels.txt'
ref,classes = read_labels(reference)
# classes :: array(['AC', 'EX1', 'EX2', 'EX3', 'IN1', 'IN2', 'MG', 'OC'], dtype=object)
result = cluster_report(ref, pred, classes)
cm = result[0]
cluster_re = result[1]
ARI_score = result[2]
NMI =result[3]
cluster = cluster_re.split('\n')
for i in cluster:
    if 'accuracy' in i:
        #print(i)
        tmp = i.split()
        #print(tmp[1])
        F1_score = tmp[1] #str
x_class = ['AC','EX1','EX2','EX3','IN1','IN2','MG','OC']
#y_class = ['AC','EX1','EX2','EX3','IN1','IN2','MG','OC']
titles = 'F1:%s    ARI:%s    NMI:%s'%(F1_score,"{:.3f}".format(ARI_score),"{:.3f}".format(NMI))
plot_confusion_matrix(cm,x_class,save= r'..\lsnmf128latent.jpg',title = titles) 

L:\newdownload\anaconda\lib\site-packages\sklearn\utils\linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)
L:\newdownload\anaconda\lib\site-packages\ipykernel_launcher.py:131: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).



## Confusion matrix ##

[[  0   0   0 112   0   0   0   8]
 [  1   1   0 187   0   0   0   1]
 [  0   0   1 365   0   0   0   0]
 [  0   0   0 515   1   1   1   1]
 [  0   0   0 193   0   0   0   2]
 [  0   0   0 316   0   0   0   4]
 [  0   0   0 125   0   0   0   1]
 [  0   0   0  28   0   0   0 224]]

## Cluster Report ##

              precision    recall  f1-score   support

          AC       0.00      0.00      0.00       120
         EX1       1.00      0.01      0.01       190
         EX2       1.00      0.00      0.01       366
         EX3       0.28      0.99      0.44       519
         IN1       0.00      0.00      0.00       195
         IN2       0.00      0.00      0.00       320
          MG       0.00      0.00      0.00       126
          OC       0.93      0.89      0.91       252

    accuracy                           0.35      2088
   macro avg       0.40      0.24      0.17      2088
weighted avg       0.45      0.35      0.22      2088


Adjusted Rand score

L:\newdownload\anaconda\lib\site-packages\ipykernel_launcher.py:166: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
